# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'WatsonApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for WatsonApp

 pod 'Firebase/Core'
 pod 'Firebase/Storage'
 pod 'FirebaseDatabase'
 pod 'SDWebImage', '~> 5.0'
 pod 'EMAlertController'
 pod 'IBMWatsonVisualRecognitionV3', '~> 2.2.0'


end
